// <auto-generated />
using EnglishFlashCardsWeb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EnglishFlashCardsWeb.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210519133009_migration_2")]
    partial class migration_2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EnglishFlashCardsWeb.Models.CardSet", b =>
                {
                    b.Property<int>("setID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("setName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("setID");

                    b.ToTable("CardSets");
                });

            modelBuilder.Entity("EnglishFlashCardsWeb.Models.FlashCard", b =>
                {
                    b.Property<int>("cardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("meaning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("senaryo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("word")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wordType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cardID");

                    b.ToTable("FlashCards");
                });
#pragma warning restore 612, 618
        }
    }
}
